// app/src/app/pages/explore/explore.component.ts
import { Component, OnInit } from "@angular/core";
import { ActivatedRoute, Router } from "@angular/router";
import { combineLatest } from "rxjs";

import { MongoDbService } from "../../services/mongo-db.service";

import { SearchParams } from "../../components/search-box/search-box.component";
import { JsonParserService } from "../../services/json-parser.service";
import { NotificationsService } from "../../services/notifications.service";

@Component({
  selector:    "app-explore",
  templateUrl: "./explore.component.html",
  styleUrls:   ["./explore.component.scss"],
})
export class ExploreComponent implements OnInit {
  server:     string;
  database:   string;
  collection: string;

  readOnly = false;
  params:     Partial<SearchParams>;
  loading = {
    content: true,
    count:   true,
  };

  count = {
    total: 0,
    start: 0,
  };
  items = [];

  constructor(
    private activatedRoute: ActivatedRoute,
    private router: Router,
    private mongoDb: MongoDbService,
    private jsonParser: JsonParserService,
    private notifService: NotificationsService,
  ) {}

  ngOnInit() {
    this.mongoDb.isReadOnly().subscribe(({ readOnly }) => {
      this.readOnly = readOnly;
    });
    combineLatest(this.activatedRoute.paramMap, this.activatedRoute.queryParamMap).subscribe(
      ([params, queryParams]) => {
        this.server = params.get("server");
        this.database = params.get("database");
        this.collection = params.get("collection");

        let query;
        let sort;
        let limit;
        let skip;
        let project;
        if (queryParams.has("query")) {
          query = queryParams.get("query");
        }
        if (queryParams.has("project")) {
          project = queryParams.get("project");
        }
        if (queryParams.has("sort")) {
          sort = queryParams.get("sort");
        }
        if (queryParams.has("skip")) {
          skip = parseInt(queryParams.get("skip"), 10);
        }
        if (queryParams.has("limit")) {
          limit = parseInt(queryParams.get("limit"), 10);
        }
        this.params = {
          query,
          sort,
          limit,
          skip,
          project,
        };
      },
    );
  }

  update(upd: boolean = true) {
    if (!this.params || !this.params.query) {
      return;
    }

    const query = JSON.stringify(this.jsonParser.parse(this.params.query));
    const sort = this.params.sort !== "" ? JSON.stringify(this.jsonParser.parse(this.params.sort)) : "{}";
    const project = this.params.project !== "" ? JSON.stringify(this.jsonParser.parse(this.params.project)) : "{}";
    if (!query || !sort) {
      return;
    }

    if (upd) {
      this.router.navigate([], {
        relativeTo:  this.activatedRoute,
        queryParams: this.params,
      });
    }

    // Set loading status
    this.loading.content = true;
    this.loading.count = true;

    // Reset status
    this.items = [];
    this.count.total = 0;

    // Load Content
    this.mongoDb
      .query(this.server, this.database, this.collection, query, project, sort, this.params.skip, this.params.limit)
      .subscribe((res: any) => {
        this.loading.content = false;

        if (res.ok) {
          this.items = res.results;
        }
      });

    // Count documents
    this.mongoDb.count(this.server, this.database, this.collection, query).subscribe((res: any) => {
      this.loading.count = false;

      if (res.ok) {
        this.count.total = res.count;
        this.count.start = this.params.skip;
      }
    });
  }

  go(documentId) {
    this.router.navigate([
      "servers",
      this.server,
      "databases",
      this.database,
      "collections",
      this.collection,
      "documents",
      documentId,
    ]);
  }

  editDocument(_id, json) {
    const partial = this.params.project && Object.keys(this.jsonParser.parse(this.params.project)).length > 0;
    const newId = json && json._id && json._id.$value;
    const oldId = _id && _id.$value;
    if (newId !== oldId) {
      this.notifService.notifyError("ObjectId changed. This is not supported, updated canceled.");
      return;
    }

    this.mongoDb.update(this.server, this.database, this.collection, oldId, json, partial).subscribe((res: any) => {
      if (res.ok) {
        this.items.forEach((item, index) => {
          const _id = item && item._id && item._id.$value;
          if (_id === oldId) {
            this.items[index] = res.update;
          }
        });
      } else {
        this.notifService.notifyError(res.message);
      }
    });
  }

  remove(_id) {
    const document = _id && _id.$value;
    if (!document) {
      return;
    }

    this.mongoDb.remove(this.server, this.database, this.collection, document).subscribe((res: any) => {
      const index = this.items.findIndex((v) => v._id && v._id.$value && v._id.$value === document);
      this.items.splice(index, 1);
    });
  }

  get hasNext() {
    return this.count.start + this.items.length < this.count.total;
  }

  next() {
    this.params.skip = this.params.skip + this.params.limit;
    this.update();
  }

  get hasPrevious() {
    return this.count.start > 0;
  }

  previous() {
    this.params.skip = Math.max(0, this.params.skip - this.params.limit);
    this.update();
  }
}

<div class="row explore-component">
  <div class="col-md-12">
    <search-box (search)="update()" [(params)]="params"></search-box>
    <panel *ngIf="params && !loading.count">
      <div class="infos">
        <div class="summary">
          <span [hidden]="count.total == 0"
            >{{ count.start + 1 | number }} - {{ count.start + items.length | number }} of </span
          >{{ count.total | number }} Documents
        </div>
        <div class="actions">
          <button class="btn btn-default" *ngIf="hasPrevious" (click)="previous()">Previous</button>
          <button class="btn btn-default" *ngIf="hasNext" (click)="next()">Next</button>
        </div>
      </div>
    </panel>
    <panel [hidden]="!loading.content">
      <h1 class="center loading">Loading...</h1>
    </panel>
    <pretty-json
      *ngFor="let item of items"
      [hidden]="loading.content"
      autoCollapse="true"
      [json]="item"
      [readOnly]="readOnly"
      (go)="go($event)"
      (edit)="editDocument(item._id, $event)"
      (remove)="remove(item._id)"
    >
    </pretty-json>
  </div>
</div>

// src/routes/servers/[server]/databases/[database]/collections/[collection]/explore/+page.svelte
<script lang="ts">
	import { goto } from "$app/navigation";
	import Panel from "$lib/components/Panel.svelte";
	import PrettyJson from "$lib/components/PrettyJson.svelte";
	import SearchBox from "$lib/components/SearchBox.svelte";
	import { notificationStore } from "$lib/stores/notifications.svelte";
	import type { MongoDocument, SearchParams } from "$lib/types";
	import { formatNumber } from "$lib/utils/filters";
	import type { PageData } from "./$types";

	let { data }: { data: PageData } = $props();

	let loading = $state({
		content: false,
		count: false,
	});

	let items = $state<MongoDocument[]>(data.results || []);
	let count = $state({
		total: data.count || 0,
		start: data.params.skip,
	});

	let params = $state<SearchParams>({ ...data.params });

	$effect(() => {
		// Update when data changes
		items = data.results || [];
		count.total = data.count || 0;
		count.start = data.params.skip;
	});

	async function update() {
		const queryParams = new URLSearchParams();
		queryParams.set("query", params.query || "{}");
		queryParams.set("sort", params.sort || "");
		queryParams.set("project", params.project || "");
		queryParams.set("skip", String(params.skip));
		queryParams.set("limit", String(params.limit));

		await goto(
			`/servers/${encodeURIComponent(data.server)}/databases/${encodeURIComponent(data.database)}/collections/${encodeURIComponent(data.collection)}/explore?${queryParams.toString()}`,
			{ invalidateAll: true },
		);
	}

	function goToDocument(documentId: string) {
		goto(
			`/servers/${encodeURIComponent(data.server)}/databases/${encodeURIComponent(data.database)}/collections/${encodeURIComponent(data.collection)}/documents/${documentId}`,
		);
	}

	async function editDocument(_id: any, json: any) {
		const partial = params.project && params.project !== "{}" && Object.keys(JSON.parse(params.project)).length > 0;
		const newId = json?._id?.$value;
		const oldId = _id?.$value;

		if (newId !== oldId) {
			notificationStore.notifyError("ObjectId changed. This is not supported, update canceled.");
			return;
		}

		try {
			const response = await fetch(
				`/api/servers/${encodeURIComponent(data.server)}/databases/${encodeURIComponent(data.database)}/collections/${encodeURIComponent(data.collection)}/documents/${oldId}${partial ? "?partial=true" : ""}`,
				{
					method: "POST",
					headers: { "Content-Type": "application/json" },
					body: JSON.stringify(json),
				},
			);

			if (response.ok) {
				const result = await response.json();
				if (result.ok) {
					notificationStore.notifySuccess("Document updated successfully");
					// Update the document in the list
					const index = items.findIndex((item) => item._id?.$value === oldId);
					if (index !== -1) {
						items[index] = result.update;
					}
				}
			} else {
				const error = await response.text();
				notificationStore.notifyError(error || "Failed to update document");
			}
		} catch (error: any) {
			notificationStore.notifyError(error.message || "Failed to update document");
		}
	}

	async function removeDocument(_id: any) {
		const documentId = _id?.$value;
		if (!documentId) return;

		try {
			const response = await fetch(
				`/api/servers/${encodeURIComponent(data.server)}/databases/${encodeURIComponent(data.database)}/collections/${encodeURIComponent(data.collection)}/documents/${documentId}`,
				{ method: "DELETE" },
			);

			if (response.ok) {
				notificationStore.notifySuccess("Document removed successfully");
				items = items.filter((item) => item._id?.$value !== documentId);
			} else {
				const error = await response.text();
				notificationStore.notifyError(error || "Failed to remove document");
			}
		} catch (error: any) {
			notificationStore.notifyError(error.message || "Failed to remove document");
		}
	}

	let hasNext = $derived(count.start + items.length < count.total);
	let hasPrevious = $derived(count.start > 0);

	function next() {
		params.skip = params.skip + params.limit;
		update();
	}

	function previous() {
		params.skip = Math.max(0, params.skip - params.limit);
		update();
	}
</script>

<div class="explore-page">
	<SearchBox {params} onsearch={update} />

	<Panel>
		<div class="infos">
			<div class="summary">
				{#if count.total > 0}
					<span>{formatNumber(count.start + 1)} - {formatNumber(count.start + items.length)} of </span>
				{/if}
				{formatNumber(count.total)} Documents
			</div>
			<div class="actions">
				{#if hasPrevious}
					<button class="btn btn-default" onclick={previous}>Previous</button>
				{/if}
				{#if hasNext}
					<button class="btn btn-default" onclick={next}>Next</button>
				{/if}
			</div>
		</div>
	</Panel>

	{#if loading.content}
		<div class="loading">Loading...</div>
	{:else}
		{#each items as item (item._id?.$value)}
			<PrettyJson
				json={item}
				autoCollapse={true}
				readOnly={data.readOnly}
				ongo={goToDocument}
				onedit={(json) => editDocument(item._id, json)}
				onremove={() => removeDocument(item._id)}
			/>
		{/each}
	{/if}
</div>

<style lang="scss">
	.explore-page {
		padding: 40px 0;
	}

	.infos {
		display: flex;
		justify-content: space-between;
		align-items: center;

		.summary {
			font-size: 16px;
		}

		.actions {
			display: flex;
			gap: 10px;
		}
	}
</style>
