// src/routes/servers/+page.svelte
<script lang="ts">
	import { addServer as addServerCommand, removeServer as removeServerCommand } from "$api/servers.remote";
	import { invalidateAll } from "$app/navigation";
	import { resolve } from "$app/paths";
	import Panel from "$lib/components/Panel.svelte";
	import TooltipTable from "$lib/components/TooltipTable.svelte";
	import { notificationStore } from "$lib/stores/notifications.svelte";
	import { formatBytes, serverName } from "$lib/utils/filters";
	import type { PageData } from "./$types";

	let { data }: { data: PageData } = $props();

	type Server = PageData["servers"][number];

	let adding = $state(false);
	let newServer = $state("");
	let loading = $state(false);
	let showRemoveModal = $state(false);
	let serverToRemove: Server | null = null;

	async function addServer() {
		if (!newServer) return;

		loading = true;
		try {
			await addServerCommand({ url: newServer });
			newServer = "";
			adding = false;
			notificationStore.notifySuccess("Server added successfully");
			// Reload the page to get updated servers
			await invalidateAll();
		} catch (error) {
			notificationStore.notifyError(error, "Failed to add server");
		} finally {
			loading = false;
		}
	}

	function openRemoveModal(server: Server) {
		serverToRemove = server;
		showRemoveModal = true;
	}

	function closeRemoveModal() {
		showRemoveModal = false;
		serverToRemove = null;
	}

	async function confirmRemove() {
		if (!serverToRemove) return;

		try {
			await removeServerCommand(serverToRemove.name);
			notificationStore.notifySuccess("Server removed successfully");
			closeRemoveModal();
			// Reload the page to get updated servers
			await invalidateAll();
		} catch (error) {
			notificationStore.notifyError(error, "Failed to remove server");
		}
	}

	function handleKeyDown(e: KeyboardEvent) {
		if (e.key === "Escape") {
			closeRemoveModal();
		}
	}
</script>

<svelte:window on:keydown={handleKeyDown} />

<Panel title="Servers">
	{#snippet actions()}
		<button class="btn btn-default btn-sm" onclick={() => (adding = !adding)}>
			{adding ? "Cancel" : "Add Server"}
		</button>
		{#if adding}
			<input
				type="text"
				placeholder="mongodb://user:password@hostname:port?directConnection=true"
				bind:value={newServer}
				disabled={loading}
				class="form-input"
			/>
			<button class="btn btn-outline-success btn-sm" onclick={addServer} disabled={!newServer.length || loading}>
				Add
			</button>
		{/if}
	{/snippet}

	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Databases</th>
				<th>Size</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{#if data.servers && data.servers.length > 0}
				{#each data.servers as server (server._id)}
					<tr class="group">
						<td>
							{#await server.details}
								<span>
									{serverName(server.name)}
								</span>
							{:then details}
								{#if "error" in details && details.error}
									<span class="error">
										<span class="badge badge-danger" title={details.error.message}>Error</span>
										{serverName(server.name)}
									</span>
								{:else}
									<a href={resolve(`/servers/${encodeURIComponent(serverName(server.name))}/databases`)}>
										{serverName(server.name)}
									</a>
								{/if}
							{/await}
						</td>
						<td>
							{#await server.details}
								<span class="text-gray-400">...</span>
							{:then details}
								{#if "databases" in details && details.databases}
									<TooltipTable
										columns={[
											{ header: "Database", key: "name" },
											{ header: "Collections", key: "collections" },
											{ header: "Size", key: "size" },
										]}
										rows={details.databases.map((db) => ({
											name: db.name,
											collections: db.collections,
											size: formatBytes(db.size),
										}))}
									>
										{details.databases.length}
									</TooltipTable>
								{/if}
							{/await}
						</td>
						<td>
							{#await server.details}
								<span class="text-gray-400">...</span>
							{:then details}
								{#if "size" in details && details.size !== undefined}
									{formatBytes(details.size)}
								{/if}
							{/await}
						</td>
						<td style="width: 140px">
							<button
								class="btn btn-outline-danger btn-sm -my-2 hidden group-hover:inline"
								onclick={() => openRemoveModal(server)}
							>
								Remove from list
							</button>
						</td>
					</tr>
				{/each}
			{:else}
				<tr>
					<td colspan="4">
						<div class="text-center">No servers...</div>
					</td>
				</tr>
			{/if}
		</tbody>
	</table>
</Panel>

{#if showRemoveModal}
	<!-- svelte-ignore a11y_click_events_have_key_events -->
	<!-- svelte-ignore a11y_no_static_element_interactions -->
	<div class="modal-overlay" onclick={closeRemoveModal}>
		<div class="modal" onclick={(e) => e.stopPropagation()}>
			<div class="modal-body">
				<p>
					Are you sure you want to remove this server? This will only remove it from this list. You can add it back.
				</p>
			</div>
			<div class="modal-footer">
				<button class="btn btn-default btn-sm" onclick={closeRemoveModal}>No</button>
				<button class="btn btn-outline-danger btn-sm" onclick={confirmRemove}>Yes</button>
			</div>
		</div>
	</div>
{/if}

<style lang="postcss">
	input[type="text"] {
		min-width: 400px;
	}
</style>

// app/src/app/pages/servers/servers.component.ts
import { Component, OnInit } from '@angular/core';
import { MongoDbService, ServerJSON } from '../../services/mongo-db.service';

@Component({
  selector: 'app-servers',
  templateUrl: './servers.component.html',
  styleUrls: ['./servers.component.scss']
})
export class ServersComponent implements OnInit {
  servers: ServerJSON[];
  
  constructor(private mongoDb: MongoDbService) { }

  ngOnInit() {
    this.mongoDb.getServers()
      .subscribe(data => {
        this.servers = data;
      });
  }

}

<div class="row servers-component">
  <panel>
    <div class="title">
      <span>Servers</span>
      <div class="actions">
        <button class="btn btn-default btn-sm" (click)="adding = !adding">
          <span *ngIf="adding">Cancel</span>
          <span *ngIf="!adding">Add Server</span>
        </button>
        <div *ngIf="adding">
          <input type="text" placeholder="user:password@hostname:port" [(ngModel)]="newServer" [disabled]="loading" />
        </div>
        <button *ngIf="adding"
                class="btn btn-outline-success btn-sm"
                (click)="addServer()"
                [disabled]="!newServer.length || loading">
          Add
        </button>
      </div>
    </div>
    <table class="table table-hover">
      <thead>
        <th>name</th>
        <th>databases</th>
        <th>size</th>
        <th></th>
      </thead>
      <tbody>
        <tr *ngFor="let server of servers" [hidden]="loading">
          <td>
            <a *ngIf="!server.error" routerLink="/servers/{{ server.name | serverName }}/databases">{{ server.name | serverName }}</a>
            <span class="error" *ngIf="server.error">
              <span class="badge badge-danger" [ngbTooltip]="server.error.message" placement="bottom">Error</span>
              {{ server.name | serverName }}
            </span>
          </td>
          <td>
            <span class="dotted"
                  *ngIf="server.databases"
                  [ngbPopover]="popContent"
                  placement="right"
                  triggers="manual"
                  #p1="ngbPopover"
                  (mouseenter)="toggle(p1, server.databases)"
                  (mouseleave)="toggle(p1)"
            >{{ server.databases.length }}</span>
          </td>
          <td><span *ngIf="server.databases">{{ server.size | bytes }}</span></td>
          <td class="actions">
            <button type="button" class="btn btn-outline-danger btn-sm" (click)="removeServer(confirmRemoval, server)">
              Remove from list
            </button>
          </td>
        </tr>
        <tr *ngIf="servers.length == 0 && !loading">
          <td colspan="4">
            <div class="center">No servers...</div>
          </td>
        </tr>
        <tr *ngIf="loading">
          <td colspan="4">
            <div class="center">Loading...</div>
          </td>
        </tr>
      </tbody>
    </table>
  </panel>

  <ng-template #popContent let-collection="collection" let-clipped="clipped">
    <table class="sm">
      <thead>
        <th>Database</th>
        <th>Collections</th>
        <th>Size</th>
      </thead>
      <tbody>
        <tr *ngFor="let item of collection">
          <td>{{ item.name }}</td>
          <td>{{ item.collections.length }}</td>
          <td>{{ item.size | bytes }}</td>
        </tr>
        <tr *ngIf="clipped">
          <td colspan=3>{{ clipped }} more items...</td>
        </tr>
      </tbody>
    </table>
  </ng-template>

  <ng-template #confirmRemoval let-modal>
    <div class="modal-body">
      <p>
        Are you sure you wan't to remove this server? This will only remove it from this list.
        You can add it back
      </p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default btn-sm" (click)="modal.close(false)">No</button>
      <button type="button" class="btn btn-outline-danger btn-sm" (click)="modal.close(true)">Yes</button>
    </div>
  </ng-template>
</div>
