// src/routes/servers/[server]/databases/[database]/collections/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import Panel from '$lib/components/Panel.svelte';
	import { formatBytes, formatNumber } from '$lib/utils/filters';

	let { data }: { data: PageData } = $props();
</script>

<div class="collections-page">
	<Panel>
		<div class="title">
			<span>Collections in {data.database}</span>
		</div>

		<table class="table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Documents</th>
					<th>Size</th>
				</tr>
			</thead>
			<tbody>
				{#if data.collections && data.collections.length > 0}
					{#each data.collections as collection}
						<tr>
							<td>
								<a
									href="/servers/{encodeURIComponent(data.server)}/databases/{encodeURIComponent(
										data.database
									)}/collections/{encodeURIComponent(
										collection.name
									)}/explore?query={encodeURIComponent('{}')}&sort=&project=&skip=0&limit=20"
								>
									{collection.name}
								</a>
							</td>
							<td>
								{#if collection.count !== undefined}
									{formatNumber(collection.count)}
								{/if}
							</td>
							<td>
								{#if collection.size !== undefined}
									{formatBytes(collection.size)}
								{/if}
							</td>
						</tr>
					{/each}
				{:else}
					<tr>
						<td colspan="3">
							<div class="center">No collections...</div>
						</td>
					</tr>
				{/if}
			</tbody>
		</table>
	</Panel>
</div>

<style lang="scss">
	.collections-page {
		padding: 40px 0;
	}
</style>

// app/src/app/pages/collections/collections.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { MongoDbService, CollectionJSON } from '../../services/mongo-db.service';

@Component({
  selector: 'app-collections',
  templateUrl: './collections.component.html',
  styleUrls: ['./collections.component.scss']
})
export class CollectionsComponent implements OnInit {
  server:      string;
  database:    string;
  collections: CollectionJSON[] = [];
  loading = true;
  
  constructor(private activatedRoute: ActivatedRoute, private mongoDb: MongoDbService) { }

  ngOnInit() {
    this.activatedRoute.paramMap.subscribe((d) => {
      this.server   = d.get("server");
      this.database = d.get("database");
      
      this.mongoDb.getCollections(this.server, this.database)
        .subscribe((collections) => {
          this.loading = false;
          this.collections = collections;
        });
    });
  }

}

<div class="row collections-component">
  <panel title="{{ database }} Collections" full-width="true">
    <table class="table table-hover">
      <thead>
        <th>name</th>
        <th>documents</th>
        <th>indexes</th>
        <th>size</th>
      </thead>
      <tbody>
        <tr *ngFor="let collection of collections">
          <td><a routerLink="/servers/{{ server }}/databases/{{ database }}/collections/{{ collection.name }}">{{ collection.name }}</a></td>
          <td>{{ collection.count | number }}</td>
          <td>{{ collection.nIndexes }}</td>
          <td>{{ collection.size | bytes }}</td>
        </tr>
         <tr *ngIf="collections.length == 0 && !loading">
          <td colspan="3">
            <div class="center">No collections...</div>
          </td>
        </tr>
        <tr *ngIf="loading">
          <td colspan="3">
            <div class="center">Loading...</div>
          </td>
        </tr>
      </tbody>
    </table>
  </panel>
</div>
